### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by BadCo-NZ** [bpetrikovics/shelly-ota#1]
Hi,

Firstly, thanks for creating a tool for updating Shellies in a locked down VLAN. I have a few now and it is tedious to check and update each one.

Now, I have pulled the script into a ubuntu 22.04 LXC and tried to run it but get the below error:

```bash
root@shelly-ota:~# ./shelly-ota.py 
Traceback (most recent call last):
  File "/root/./shelly-ota.py", line 11, in <module>
    import lib.venvtools as venvtools
ModuleNotFoundError: No module named 'lib.venvtools'
```

I have installed all the dependencies in [requirements.txt](https://github.com/bpetrikovics/shelly-ota/blob/main/requirements.txt) as well as `venvtools` but still get the same error, any suggestions?

Thanks

**Comment by BadCo-NZ** [comment]
Also just tried after install `python3-venv` and got the same error.

**Comment by BadCo-NZ** [comment]
Someone noted the `lib` folder in the repo and suggested cloning and running the script, but I got the same error.

**Comment by bpetrikovics** [comment]
Yes, you need to clone the repository as a whole since venvtools is part of the app, living under lib/.

The easiest way to use this in a completely new environment with virtualenv is:

`git clone https://github.com/bpetrikovics/shelly-ota.git`
`virtualenv -p pyhon3  shelly-ota/`
`cd shelly-ota`
`. bin/activate`
`pip install -r requirements.txt`

I will extend the documentation a bit to make things clearer. Hope this helps!

**Comment by BadCo-NZ** [comment]
Yup, that did the trick!

For reference, I *only* needed `git` and `python3-virutalenv` for this LXC.
